name: Automated Release Process

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name for Release'
        required: true
      release_title:
        description: 'Title for the Release'
        required: true
      release_notes:
        description: 'Release Notes'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event_name == 'push' && github.ref_name || github.event.inputs.tag_name }}
          release_name: ${{ github.event_name == 'push' && 'Release ' + github.ref_name || github.event.inputs.release_title }}
          body: ${{ github.event_name == 'push' && 'Automatic release of ' + github.ref_name || github.event.inputs.release_notes }}
          draft: false
          prerelease: false
