name: Automatic Versioning

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures you fetch all the history for all branches and tags

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.38.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true
        RELEASE_BRANCHES: main
        CUSTOM_TAG: ${{ github.event.head_commit.message }}
